
(() => {
  const normalisePostcode = value => String(value || "")
    .toUpperCase().replace(/[^A-Z0-9 ]/g, " ").replace(/\s+/g, " ").trim();

  const postcodeSector = value => {
    const pc = normalisePostcode(value);
    const match = pc.match(/^([A-Z]{1,2}\d[A-Z\d]?)\s*(\d)(?:[A-Z]{2})?$/);
    return match ? `${match[1]} ${match[2]}` : "";
  };

  const routingData = () => window.HERITAGE_POSTCODE_ROUTING || window.HERITAGE_ROUTING || {national:{email:"care@heritagehealthcare.co.uk",name:"National Office"},offices:{}};

  const findOffice = postcode => {
    const sector = postcodeSector(postcode);
    if (!sector) return {status:"invalid", office:null, sector:"", matches:[]};

    const matches = Object.entries(routingData().offices)
      .filter(([, office]) => Array.isArray(office.postcodes) && office.postcodes.includes(sector))
      .map(([slug, office]) => ({slug, ...office}));

    if (matches.length === 1) {
      const office=matches[0];
      return office.email
        ? {status:"local", office, sector, matches}
        : {status:"local-no-email", office, sector, matches};
    }

    if (matches.length > 1) return {status:"ambiguous", office:null, sector, matches};
    return {status:"national", office:null, sector, matches:[]};
  };

  const encode = value => encodeURIComponent(String(value || ""));

  const buildMailto = (route, form) => {
    const data = new FormData(form);
    const national=routingData().national;
    const destination = route.status === "local" ? route.office.email : national.email;
    const subjectPrefix = route.status === "local"
      ? `New care enquiry — ${route.office.name}`
      : route.status === "local-no-email"
        ? `Care enquiry — ${route.office.name} — National routing required`
        : route.status === "ambiguous"
          ? `Care enquiry — National Office — multiple coverage matches`
          : `Care enquiry — National Office`;

    const matched = route.office?.name || (route.matches||[]).map(x=>x.name).join(", ") || "National Office";
    const body = [
      "HERITAGE HEALTHCARE — NEW CARE ENQUIRY","",
      `Source page/location: ${data.get("source_office") || "Main website"}`,
      `Routing result: ${route.status}`,
      `Postcode sector: ${route.sector || "Not verified"}`,
      `Matched office(s): ${matched}`,
      "",
      `Name: ${data.get("name") || ""}`,
      `Email: ${data.get("email") || ""}`,
      `Phone: ${data.get("phone") || ""}`,
      `Person requiring care: ${data.get("person") || ""}`,
      `Postcode: ${data.get("postcode") || ""}`,
      `Care required: ${data.get("care_type") || ""}`,
      "",
      "Message:", `${data.get("message") || ""}`,"",
      "This enquiry was generated by the Heritage Healthcare website prototype."
    ].join("\n");
    return `mailto:${destination}?subject=${encode(subjectPrefix)}&body=${encode(body)}`;
  };

  const saveToCRM = (route, form) => {
    try {
      const STORAGE="heritageCRM_v1";
      const raw=localStorage.getItem(STORAGE);
      const db=raw?JSON.parse(raw):{enquiries:[]};
      if(!Array.isArray(db.enquiries)) db.enquiries=[];
      const data=new FormData(form);
      const officeId=route.status==="local" || route.status==="local-no-email" ? route.office.slug : null;
      const id="HH-"+new Date().getFullYear()+"-"+String(db.enquiries.length+189).padStart(6,"0");
      db.enquiries.push({
        id,officeId,sourceOffice:data.get("source_office")||"Main website",
        name:data.get("name")||"",email:data.get("email")||"",phone:data.get("phone")||"",
        person:data.get("person")||"",postcode:data.get("postcode")||"",
        careType:data.get("care_type")||"",message:data.get("message")||"",
        status:"new",assignedTo:officeId?`${officeId}-manager`:"national-admin",
        routingStatus:route.status,postcodeSector:route.sector,
        matchedOffice:route.office?.name || (route.matches||[]).map(x=>x.name).join(", ") || "National Office",
        createdAt:new Date().toISOString(),notes:[]
      });
      localStorage.setItem(STORAGE,JSON.stringify(db));
      return id;
    } catch(e) { return null; }
  };

  window.HeritageRouting = {normalisePostcode, postcodeSector, findOffice, buildMailto, saveToCRM};

  document.addEventListener("DOMContentLoaded", () => {
    document.querySelectorAll("[data-enquiry-form]").forEach(form => {
      const sourceOffice = form.dataset.sourceOffice || "";
      const postcode = form.querySelector("[name=postcode]");
      const result = form.querySelector("[data-routing-result]");
      const success = form.querySelector("[data-form-success]");

      const updateRoute = () => {
        const route = findOffice(postcode?.value);
        const routingField=form.querySelector("[name=routing]");
        const matchedField=form.querySelector("[name=matched_office]");
        const emailField=form.querySelector("[name=route_email]");
        if(routingField) routingField.value=route.status;
        if(matchedField) matchedField.value=route.office?.name || (route.matches||[]).map(x=>x.name).join(", ") || "National Office";
        if(emailField) emailField.value=route.office?.email || routingData().national.email;
        if (!result) return route;
        if (!postcode?.value) { result.className="routing-result"; result.innerHTML=""; return route; }
        result.className="routing-result show";
        if (route.status === "local") {
          result.innerHTML=`<strong>✓ Local coverage confirmed</strong><span>Your enquiry will be routed to ${route.office.name}.</span>`;
        } else if (route.status === "local-no-email") {
          result.innerHTML=`<strong>✓ Coverage confirmed</strong><span>This postcode is covered by ${route.office.name}. It will be recorded against that office and flagged for National Office until the office email is configured.</span>`;
        } else if (route.status === "ambiguous") {
          result.innerHTML=`<strong>National review</strong><span>This postcode appears in more than one coverage list. National Office will review and route the enquiry.</span>`;
        } else if (route.status === "national") {
          result.innerHTML=`<strong>National review</strong><span>This postcode is not in the verified coverage data currently loaded. The enquiry will be routed to National Office.</span>`;
        } else {
          result.innerHTML=`<strong>Postcode check</strong><span>Enter a full UK postcode, for example YO24 1AA. If it cannot be verified, National Office will review it.</span>`;
        }
        return route;
      };

      postcode?.addEventListener("input", updateRoute);
      postcode?.addEventListener("blur", updateRoute);

      form.addEventListener("submit", event => {
        event.preventDefault();
        const route=updateRoute();
        saveToCRM(route,form);
        const mailto=buildMailto(route,form);
        window.location.href=mailto;
        if(success){
          const destination=route.status==="local" ? route.office.email : routingData().national.email;
          success.innerHTML=`<strong>Your email app is opening.</strong><br>The enquiry has been captured in the CRM and routed to <b>${route.office?.name || "National Office"}</b>. If nothing opens, please email <b>${destination}</b> directly.`;
          success.classList.add("show");
        }
      });
    });
  });
})();
