
(() => {
  const normalisePostcode = value => String(value || "")
    .toUpperCase().replace(/[^A-Z0-9 ]/g, " ").replace(/\s+/g, " ").trim();

  const postcodeSector = value => {
    const pc = normalisePostcode(value);
    const match = pc.match(/^([A-Z]{1,2}\d[A-Z\d]?)\s*(\d)$/);
    return match ? `${match[1]} ${match[2]}` : "";
  };

  const findOffice = (postcode, sourceOffice) => {
    const sector = postcodeSector(postcode);
    if (!sector) return {status:"invalid", office:null, sector:""};

    const matches = Object.entries(window.HERITAGE_ROUTING.offices)
      .filter(([, office]) => office.coverage_verified && office.postcodes.includes(sector));

    const sourceMatch = matches.find(([slug]) => slug === sourceOffice);
    if (sourceMatch) return {status:"local", office:{slug:sourceMatch[0], ...sourceMatch[1]}, sector};

    if (matches.length) return {status:"other-office", office:{slug:matches[0][0], ...matches[0][1]}, sector};

    return {status:"national", office:null, sector};
  };

  const encode = value => encodeURIComponent(String(value || ""));

  const buildMailto = (route, form) => {
    const data = new FormData(form);
    const destination = route.status === "local"
      ? route.office.email
      : window.HERITAGE_ROUTING.national.email;

    const subjectPrefix = route.status === "local"
      ? `New care enquiry — ${route.office.name}`
      : `Care enquiry — National Office`;

    const body = [
      "HERITAGE HEALTHCARE — NEW CARE ENQUIRY",
      "",
      `Source page/location: ${data.get("source_office") || "Main website"}`,
      `Routing result: ${route.status}`,
      `Postcode sector: ${route.sector || "Not verified"}`,
      `Matched office: ${route.status === "local" ? route.office.name : route.status === "other-office" ? `National Office — suggested ${route.office.name}` : "National Office"}`,
      "",
      `Name: ${data.get("name") || ""}`,
      `Email: ${data.get("email") || ""}`,
      `Phone: ${data.get("phone") || ""}`,
      `Person requiring care: ${data.get("person") || ""}`,
      `Postcode: ${data.get("postcode") || ""}`,
      `Care required: ${data.get("care_type") || ""}`,
      "",
      "Message:",
      `${data.get("message") || ""}`,
      "",
      "This enquiry was generated by the Heritage Healthcare website prototype."
    ].join("\n");

    return `mailto:${destination}?subject=${encode(subjectPrefix)}&body=${encode(body)}`;
  };

  window.HeritageRouting = {normalisePostcode, postcodeSector, findOffice, buildMailto};

  document.addEventListener("DOMContentLoaded", () => {
    document.querySelectorAll("[data-enquiry-form]").forEach(form => {
      const sourceOffice = form.dataset.sourceOffice || "";
      const postcode = form.querySelector("[name=postcode]");
      const result = form.querySelector("[data-routing-result]");
      const success = form.querySelector("[data-form-success]");

      const updateRoute = () => {
        const route = findOffice(postcode?.value, sourceOffice);
        if (!result) return;

        if (!postcode?.value) {
          result.className = "routing-result";
          result.innerHTML = "";
          return route;
        }

        result.className = "routing-result show";
        if (route.status === "local") {
          result.innerHTML = `<strong>✓ Local coverage confirmed</strong><span>Your enquiry will be addressed to ${route.office.name}.</span>`;
        } else if (route.status === "other-office") {
          result.innerHTML = `<strong>✓ Heritage coverage found</strong><span>This postcode is listed for ${route.office.name}. The enquiry will be addressed to National Office for review, with ${route.office.name} suggested.</span>`;
        } else if (route.status === "national") {
          result.innerHTML = `<strong>National review</strong><span>This postcode is not in the verified coverage data currently loaded into this prototype. The enquiry will be addressed to National Office.</span>`;
        } else {
          result.innerHTML = `<strong>Postcode check</strong><span>Enter a full UK postcode, for example YO24 1AA. If it cannot be verified, you can still submit and National Office will review it.</span>`;
        }
        return route;
      };

      postcode?.addEventListener("input", updateRoute);
      postcode?.addEventListener("blur", updateRoute);

      form.addEventListener("submit", event => {
        event.preventDefault();

        const route = updateRoute();
        const mailto = buildMailto(route, form);

        // Static-site behaviour: opens the user's configured email client with
        // the correct recipient and a fully populated enquiry. This is a real
        // send workflow once the user clicks Send in their mail application.
        window.location.href = mailto;

        if (success) {
          success.innerHTML = `<strong>Your email app is opening.</strong><br>The enquiry has been addressed to the routed office. If nothing opens, please email <b>${route.status === "local" ? route.office.email : window.HERITAGE_ROUTING.national.email}</b> directly.`;
          success.classList.add("show");
        }
      });
    });
  });
})();
